import './globals.css'
import { Montserrat } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import Navbar from './components/navbar/Navbar'
import { dark , light } from '@clerk/themes'

const monte = Montserrat({ subsets: ['latin'] , weight:['100','200','500'] })

export const metadata = {
  title: 'CMS BLOG APP',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <ClerkProvider appearance={{
      baseTheme: 'light',
    }}>
    <html lang="en">
      <body className={monte.className}>
      <Navbar/>
      <div className='main'>
      {children}
      </div>
      </body>
    </html>
    </ClerkProvider>
  )
}
